name: "SCA Tool - GitHub Action"
description: "Send your project to SCA Tool to get a full view of the status of your project without the need to manually start a scan."
author: "SCA Tool"
icon;: "arrow-up-circle"
color: "green"
inputs:
  api_url:
    description: "The URL of the API to fetch file extensions."
    required: false
    default: "https://app.scatool.com/api/v1/"
  excluded_paths:
    description: "Comma-separated list of paths to exclude from the scan."
    required: false
    default: "node_modules/**, dist/**"
  api_key:
    description: "API key for authentication."
    required: true
  code_unit_id:
    description: "Unique identifier for the code unit."
    required: true
  github_token:
    description: "GitHub token to post the link to the result as comment when possible. If not specified, the link will only be pronted in the console."
    required: false
outputs:
  string:
    description: "Success string. Later the url of the scan will be added here."
runs:
  using: "node20"
  main: "dist/index.js"
